# Generated by Django 4.1.5 on 2023-06-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myModel',
            new_name='event',
        ),
    ]
