# Generated by Django 4.1.5 on 2023-06-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0003_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
