# Generated by Django 4.1.5 on 2023-07-01 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0004_alter_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
