# Generated by Django 4.1.5 on 2023-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0006_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.TextField(verbose_name='(website that the "register" button goes to. make sure to include https://www.'),
        ),
    ]
