# Generated by Django 4.1.5 on 2023-07-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0008_alter_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.TextField(verbose_name='link (website that the "register" button goes to. make sure to include "https://www." in the website address)'),
        ),
    ]
