# Generated by Django 4.1.5 on 2023-07-01 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0009_alter_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='name (what you want this event to be called in the admin interface)'),
            preserve_default=False,
        ),
    ]
