# Generated by Django 4.1.5 on 2023-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0011_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name (what you want this event to be called in the admin interface)')),
                ('title', models.TextField()),
                ('desc', models.TextField(verbose_name='description (should be around 1 sentence long)')),
                ('img', models.ImageField(upload_to='images/', verbose_name='image')),
                ('link', models.TextField(verbose_name='link (website that the "register" button goes to. make sure to include "https://" in the website address)')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.TextField(verbose_name='link (website that the "register" button goes to. make sure to include "https://" in the website address)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.TextField(verbose_name='link (website that the "register" button goes to. make sure to include "https://" in the website address)'),
        ),
    ]
