# Generated by Django 4.2.4 on 2023-08-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0012_card_alter_event_link_alter_slide_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
