# Generated by Django 4.2.4 on 2023-08-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0013_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=models.TextField(verbose_name='description (should be around 1-2 sentences long)'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='desc',
            field=models.TextField(verbose_name='description (should be around 1-2 sentences long)'),
        ),
    ]
