# Generated by Django 4.2.4 on 2023-10-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0014_alter_card_desc_alter_slide_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='button',
            field=models.TextField(default=0, verbose_name="text that is in the button, for example 'register'"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.TextField(verbose_name='link (website that the button goes to. make sure to include "https://" in the website address)'),
        ),
    ]
