# Generated by Django 4.2.4 on 2023-10-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classfive', '0015_slide_button_alter_slide_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='button',
            field=models.TextField(verbose_name="text that is in the button, for example 'register'. all caps suggested"),
        ),
    ]
